# 包含语法产生式的文本文件路径
grammar: "examples/grammars/simple-grammar-lr0.txt"
# 输入字符串，以空格分隔
string: "a b"
# 语法分析算法. Choices = ['ll1', 'lr0', 'slr1', 'lr1', 'lalr1']
parsing_algo: lr0
# 是否导出语法分析表 ?
parsing-table: True
# 是否导出语法树 ?
vis-tree: True
# 是否可视化生成的 LR 自动机 ? (仅对 LR 语法分析有效)
vis-automaton: True
# 是否可视化语法分析过程 ? (将使用 `manim` 进行动画)
vis-parsing: True
# 可视化视频质量. Choices = ['480p', '720p', '1080p', '1440p', '2160p']
manim-video-quality: "480p"
